branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

node_js:
  - "8"
  - "6"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

git:
  depth: 1

install:
  - npm install
  - npm install coveralls --save-dev
  - npm run build
  - cd example
  - npm install
  - npm run build
  - npm pack

script:
  - npm run nyc-ci
  - npm run coverage
