branches:
  only:
    - master

language: node_js

os:
  - linux

sudo: false

node_js:
  - "12"
  - "10"
  - "8"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

git:
  depth: 1

install:
  - npm install
  - npm run build
  - cd example
  - npm install
  - npm run build
  - cd ..
  - npm pack

script:
  - if [ $TRAVIS_NODE_VERSION == "8" ]; then
      npm install coveralls --save-dev;
      npm run nyc-ci;
      npm run coverage;
    else
      npm run test;
    fi
